### ISSUE TITLE
NPM ls returns an error, breaking the script

### ISSUE THREAD

**Issue by RHeynsZa** [fosslight/fosslight_dependency_scanner#131]
**Describe the bug**
The package fails, because `npm ls -a` will [return a non-zero code](https://github.com/npm/npm/issues/17624) if any dependencies are missing or misaligned. I currently use Yarn, and license-checker works fine without issue. However, this package seems to use `npm ls` to get a list of all packages, to build the output. Even though my software works fine, while some packages are still outdated, `npm ls` willl error, making this package unusable. 

**To Reproduce**
Currently my packages having issues, is google-maps-react which is running at a lower version than the react version its attached to, react 18.
So install 
- google-map-react@^1.1.7
- react@^17.0.2

**Expected behavior**
Intended usage of `npm ls` aside, for the usage it has in this package, the error doesnt mean anything. The list is there, it is complete, and thus the error should not impact this package.

**System environment (please complete the following information):**
 - OS: Ubuntu 22
 - Python : python3.8

**Comment by dd-jy** [comment]
@RHeynsZa 
FOSSLight Dependency Scanner uses 'npm ls -a' to extract the relationship of dependencies like direct/transtivie type. 
So I fixed the issue so that direct/transitive dependency information is not printed when the 'npm ls' command fails.

Could you test it with building local package?
```
// activate virtualenv
virtualenv -p python3 venv_test
sourace venv_test/bin/activate

// build local package with bug_fix source
git clone https://github.com/fosslight/fosslight_dependency_scanner.git
cd fosslight_dependency_scanner
git checkout -b bug_fix -t origin/bug_fix
pip install .

// move the path for your test source codes and run fosslight_dependency_scanner
cd {test_source_code_path}
fosslight_dependency
```

**Comment by RHeynsZa** [comment]
No luck unfortunately, I think the error happens before your fix

log here:
```
[FOSSLIGHT_DEPENDENCY] Tool Info : fosslight_dependency v3.13.1
[FOSSLIGHT_DEPENDENCY] Found the manifest file(package.json) automatically.
[FOSSLIGHT_DEPENDENCY] ### Set Package Manager = npm
npm ERR! code ELSPROBLEMS
npm ERR! invalid: react-dom@17.0.2 /home/........./node_modules/react-dom
npm ERR! invalid: react@17.0.2 /home/......../node_modules/react
npm ERR! invalid: date-fns@1.30.1 /home/............../node_modules/date-fns
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "invalid: react-dom@17.0.2 /home/.............../node_modules/react-dom\ninvalid: react@17.0.2 /home/............../node_modules/react\ninvalid: date-fns@1.30.1 /home/............./node_modules/date-fns",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/........./.npm/_logs/2023-04-13T08_24_32_527Z-debug-0.log
Cannot print direct/transitive dependency: Command 'npm ls -a --prod --json' returned non-zero exit status 1.
Parse oss information with file: tmp_npm_license_output.json
### Complete to analyze: npm
[FOSSLIGHT_DEPENDENCY] Writing Output file(/home/................../fosslight_report_dep_230413_1024.xlsx), success:True
[FOSSLIGHT_DEPENDENCY] ### FINISH ###
```

**Comment by RHeynsZa** [comment]
I make PR
