### ISSUE TITLE
If virtualenv is not installed in python, the message is the same as undetected

### ISSUE THREAD

**Issue by Hosim33** [fosslight/fosslight_dependency_scanner#209]
**Describe the bug**
Failure to create virtualenv If an error occurs, the message Nothing is detected from the scanner so output file is not generated. This can be mistaken for the user not being detected and not being output.

**To Reproduce**
Delete the venv folder from the Lib folder of the path where Python is installed and run fosslight_dependency_scanner.

**Expected behavior**
Virtualenv creation failure If an error occurs, a message should be printed asking you to have a virtualenv environment.

**System environment (please complete the following information):**
 - OS: Windows
 - Python : python3.9

**Comment by Hosim33** [comment]
A bug that occurred in v3.13.9 appears to have been done in v3.15.4 by presenting a link to the fosslight guide.

**Comment by soimkim** [comment]
@Hosim33 , Thank you for confirming that it cannot be reproduced. 😃
