### ISSUE TITLE
Column name not output in csv format

### ISSUE THREAD

**Issue by Hosim33** [fosslight/fosslight_dependency_scanner#212]
**Describe the bug**
When it is an Excel format, the column name is output correctly, but when it is a csv format, the column name is not output correctly.

**To Reproduce**
If you set the option to "-f csv" in the fosslight_dependency_scanner to open and check the generated csv file after running, there is no column name.

**Expected behavior**
The column name should be output in the same way as when output in excel format.

**System environment (please complete the following information):**
 - OS: Windows
 - Python : python3.9

**Comment by Hosim33** [comment]
fosslight util(https://github.com/fosslight/fosslight_util/pull/171)에서 수정하였습니다.

**Comment by soimkim** [comment]
수정된 건으로 Close합니다.
