### ISSUE TITLE
android gradle 플러그인 링크가 깨진 것 같습니다

### ISSUE THREAD

**Issue by dasomhan** [fosslight/fosslight_dependency_scanner#32]
https://jcenter.bintray.com/ 링크가 403 에러 뜨는데 레포지토리 확인 부탁 드립니다...!

**Comment by dd-jy** [comment]
@dasomhan 님,
jcenter repository가 2021년 5월 1일부터 read-only repository로 변경되어 직접 접근 불가능하도록 변경된 것으로 확인됩니다.
이에 따라 FL dependency에서 이용하는 com.lge.android.licensetools:android-dependency-scanning 라이브러리는 추후 mavenCentral()로 repository 변경하여 다시 release하도록 하겠습니다. 
그런데 https://fosslight.org/fosslight-guide-en/scanner/2_dependency.html#android-gradle 가이드에 따라 실행 시 에러가 발생한다던지 문제가 발생하고 있는 상황인가요??

**Comment by dd-jy** [comment]
@dasomhan 님,
[android-dependency-scanning](https://github.com/fosslight/android-dependency-scanning) 플러그인이 mavenCentral 레파지토리로 배포되었습니다.
업데이트된 android 사용 가이드 참조부탁드립니다. (http://10.177.235.45:4000/scanner/2_dependency.html#android-gradle)
