### ISSUE TITLE
   Error while using Android Gradle plugin for dependency scanner

### ISSUE THREAD

**Issue by kwmyoo** [fosslight/fosslight_dependency_scanner#33]
First of all, the official guide page doesn't specify which option one should use in the command line ("-m") for Android Gradle. The guide only shows the option "-m gradle", but it seems like one should use "-m android" in order to properly use the Android Gradle plugin for FOSSLight Dependency Scanner.

Secondly, when I try to scan the dependencies for Android gradle using the command `fosslight_dependency -m android`, it outputs the error:
```
### Error Message ###
app/android_dependency_output.txt doesn't exist in this directory.
Please check the below thing first.
  1.Did you run the license-maven-plugin?
  2.Or if your project has the customized build output directory,                     then use '-c' option with your customized build output directory name
    $ fosslight_dependency -c output
```
The above error occurs even though I completed the plugin setup step for Android Gradle in the following link: [https://fosslight.org/fosslight-guide/scanner/2_dependency.html#android-gradle](url)

**Comment by dd-jy** [comment]
@kwmyoo ,
Thank you for reporting the issues! I'll let you know after fixing it.

**Comment by dd-jy** [comment]
@kwmyoo 
We fixed the issues for '-m' option and update the android user guide(https://fosslight.org/fosslight-guide/scanner/2_dependency.html#android-gradle).
