### ISSUE TITLE
Support Go package management

### ISSUE THREAD

**Issue by syleeeee** [fosslight/fosslight_dependency_scanner#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Would be great if fosslight dependency scanner also supports Go platform as well. 

**Describe alternatives you've considered**
I searched online, and found these two libraries for Go.
- https://github.com/tawesoft/gocomply
- https://github.com/google/go-licenses

Even if I adopt one of these, I have to re-organize the result to import them to Fosslight anyway.

**Additional context**

**Comment by dd-jy** [comment]
@syleeeee 
I reviewed the two tools for analyzing packages of go.
- https://github.com/tawesoft/gocomply
- https://github.com/google/go-licenses
Neither tool can extract the information for FOSSLight report (ex, oss version, license name (gocomply printed the whole of license text)).

So we want to implement it ourselves.
1. The latest go project seems to use the go module. So we only want to support the Go projects that have go.mod file.
2. The package list obtained through the command('go list -m all') seems to be the entire package list (including direct and transitive packages). So, for these lists, we want to fill in the package information in the FOSSLight Report form.
3. You will obtain license information from https://pkg.go.dev/{package path}.

Before starting it, I would like to ask to Go developer to confirm that this is correct. Could you please ask the Go developer the following questions?
1. Whether the 'go list -m all' command is correct to print the entire package
2. Make sure that the 'go list -m all' command can be run on the entire go project.

**Comment by syleeeee** [comment]
@dd-jy Thanks for all these investigations, sounds great to me! 
I asked a favor to Go developers in LINE, so I guess someone will leave comments soon :)

**Comment by brew0722** [comment]
looks good to me. It seems same results when compared to the [`go mod graph`](https://go.dev/ref/mod#go-mod-graph).
If you want to see detailed dependencies graph, this command is also recommended.

**Comment by zemyblue** [comment]
`go modules` is supported from go 1.11 version.
https://go.dev/blog/using-go-modules

**Comment by egonspace** [comment]
1. Whether the 'go list -m all' command is correct to print the entire package ->  It’s correct.
2. Make sure that the 'go list -m all' command can be run on the entire go project. -> It's right.

**Comment by dd-jy** [comment]
@syleeeee 
This feature merged to the main branch. and it will be released in next week!
